### ISSUE TITLE
How to handle releases per action?

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/bats-library#10]
What are peoples thoughts on how we do GitHub releases for this repo? I am presuming each release would follow a naming of:
- {lib}-{verison}

i.e.: yaml-json-manipulation-1.0.0

but thought I'd see if anyone else has other ideas?

cc @springdo  @pabrahamsson

**Comment by garethahealy** [comment]
The original idea is maybe overthinking it as since this repo will be added as a dep to another repo as a whole which makes it hard to version each lib, so maybe just best to keep it simple and version the whole repo.

**Comment by springdo** [comment]
You're probs correct - I cannot imagine this repo getting so monstrous that it required individual lib versioning.
