### ISSUE TITLE
🏄‍♂️ Create a DEVELOPMENT.md file 

### ISSUE THREAD

**Issue by springdo** [redhat-cop/bats-library#13]
Create instructions for contributing, testing and linting things etc 

FYI @garethahealy

**Comment by garethahealy** [comment]
@springdo ; i've added a testing.md file via this PR:
- https://github.com/redhat-cop/bats-library/pull/11
- https://github.com/redhat-cop/bats-library/blob/06e630ff36be68f248b2bad9c6519aabf25b0ccb/TESTING.md

Look good for the first pass to close this issue?
