### ISSUE TITLE
question: helm lint after helm template - why?

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/bats-library#38]
@jfilipcz in PR https://github.com/redhat-cop/bats-library/pull/36/files you added linting. but helm lint is called _after_ helm template. if there are any issues with the chart, helm template will fail printing out the reason which seems to negate the need for helm lint.

https://github.com/redhat-cop/bats-library/blob/master/src/helm.bash#L32-L40

if helm lint is needed, shouldn't it go before helm template? or am I missing something.

**Comment by garethahealy** [comment]
@jfilipcz thoughts on the above question?

**Comment by jfilipcz** [comment]
@garethahealy - I think the idea was to replicate original behavior of test of doing `helm template` first, and then yq verification of the output temp file. `helm lint` has the same effect - although I do agree it looks a bit awkward in that order.
